// Code generated by DIGEN; DO NOT EDIT.
// This file was generated by Dependency Injection Container Generator 0.4.0.
// See docs at https://github.com/strider2038/digen
package lookup

import (
	"context"
	pgxpool "github.com/jackc/pgx/v5/pgxpool"
	entryHandler "github.com/mkheyfets/ispro-app/internal/entities/entry"
	entryRepo "github.com/mkheyfets/ispro-app/internal/entities/entry/repository"
	linkHandler "github.com/mkheyfets/ispro-app/internal/entities/link"
	linkRepo "github.com/mkheyfets/ispro-app/internal/entities/link/repository"
	restapi "github.com/mkheyfets/ispro-app/internal/restapi"
	operations "github.com/mkheyfets/ispro-app/internal/restapi/operations"
	validation "github.com/muonsoft/validation"
)

type Container interface {
	// SetError sets the first error into container. The error is used in the public container to return an initialization error.
	// Deprecated. Return error in factory instead.
	SetError(err error)

	DSN(ctx context.Context) string
	Pool(ctx context.Context) *pgxpool.Pool
	Validator(ctx context.Context) *validation.Validator
	EntryRepository(ctx context.Context) *entryRepo.PostgresRepository
	LinkRepository(ctx context.Context) *linkRepo.PostgresLinkRepository
	EntryHandler(ctx context.Context) *entryHandler.Handler
	LinkHandler(ctx context.Context) *linkHandler.Handler
	API(ctx context.Context) *operations.IsproAppAPI
	Server(ctx context.Context) *restapi.Server
}
