// Code generated by go-swagger; DO NOT EDIT.

package entries

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
)

// NewListEntriesParams creates a new ListEntriesParams object
//
// There are no default values defined in the spec.
func NewListEntriesParams() ListEntriesParams {

	return ListEntriesParams{}
}

// ListEntriesParams contains all the bound params for the list entries operation
// typically these are obtained from a http.Request
//
// swagger:parameters listEntries
type ListEntriesParams struct {
	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewListEntriesParams() beforehand.
func (o *ListEntriesParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
