// Code generated by go-swagger; DO NOT EDIT.

package entries

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/mkheyfets/ispro-app/models"
)

// UpdateEntryOKCode is the HTTP code returned for type UpdateEntryOK
const UpdateEntryOKCode int = 200

/*
UpdateEntryOK Entry updated

swagger:response updateEntryOK
*/
type UpdateEntryOK struct {

	/*
	  In: Body
	*/
	Payload *models.Entry `json:"body,omitempty"`
}

// NewUpdateEntryOK creates UpdateEntryOK with default headers values
func NewUpdateEntryOK() *UpdateEntryOK {

	return &UpdateEntryOK{}
}

// WithPayload adds the payload to the update entry o k response
func (o *UpdateEntryOK) WithPayload(payload *models.Entry) *UpdateEntryOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update entry o k response
func (o *UpdateEntryOK) SetPayload(payload *models.Entry) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateEntryOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateEntryNotFoundCode is the HTTP code returned for type UpdateEntryNotFound
const UpdateEntryNotFoundCode int = 404

/*
UpdateEntryNotFound Entry not found

swagger:response updateEntryNotFound
*/
type UpdateEntryNotFound struct {
}

// NewUpdateEntryNotFound creates UpdateEntryNotFound with default headers values
func NewUpdateEntryNotFound() *UpdateEntryNotFound {

	return &UpdateEntryNotFound{}
}

// WriteResponse to the client
func (o *UpdateEntryNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) // Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
