// Code generated by go-swagger; DO NOT EDIT.

package operations

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/loads"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/runtime/security"
	"github.com/go-openapi/spec"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/mkheyfets/ispro-app/internal/restapi/operations/entries"
	"github.com/mkheyfets/ispro-app/internal/restapi/operations/links"
)

// NewIsproAppAPI creates a new IsproApp instance
func NewIsproAppAPI(spec *loads.Document) *IsproAppAPI {
	return &IsproAppAPI{
		handlers:            make(map[string]map[string]http.Handler),
		formats:             strfmt.Default,
		defaultConsumes:     "application/json",
		defaultProduces:     "application/json",
		customConsumers:     make(map[string]runtime.Consumer),
		customProducers:     make(map[string]runtime.Producer),
		PreServerShutdown:   func() {},
		ServerShutdown:      func() {},
		spec:                spec,
		useSwaggerUI:        false,
		ServeError:          errors.ServeError,
		BasicAuthenticator:  security.BasicAuth,
		APIKeyAuthenticator: security.APIKeyAuth,
		BearerAuthenticator: security.BearerAuth,

		JSONConsumer: runtime.JSONConsumer(),

		JSONProducer: runtime.JSONProducer(),

		EntriesCreateEntryHandler: entries.CreateEntryHandlerFunc(func(params entries.CreateEntryParams) middleware.Responder {
			_ = params

			return middleware.NotImplemented("operation entries.CreateEntry has not yet been implemented")
		}),

		LinksCreateLinkHandler: links.CreateLinkHandlerFunc(func(params links.CreateLinkParams) middleware.Responder {
			_ = params

			return middleware.NotImplemented("operation links.CreateLink has not yet been implemented")
		}),

		EntriesDeleteEntryHandler: entries.DeleteEntryHandlerFunc(func(params entries.DeleteEntryParams) middleware.Responder {
			_ = params

			return middleware.NotImplemented("operation entries.DeleteEntry has not yet been implemented")
		}),

		LinksDeleteLinkHandler: links.DeleteLinkHandlerFunc(func(params links.DeleteLinkParams) middleware.Responder {
			_ = params

			return middleware.NotImplemented("operation links.DeleteLink has not yet been implemented")
		}),

		EntriesGetEntryHandler: entries.GetEntryHandlerFunc(func(params entries.GetEntryParams) middleware.Responder {
			_ = params

			return middleware.NotImplemented("operation entries.GetEntry has not yet been implemented")
		}),

		LinksGetLinkHandler: links.GetLinkHandlerFunc(func(params links.GetLinkParams) middleware.Responder {
			_ = params

			return middleware.NotImplemented("operation links.GetLink has not yet been implemented")
		}),

		EntriesListEntriesHandler: entries.ListEntriesHandlerFunc(func(params entries.ListEntriesParams) middleware.Responder {
			_ = params

			return middleware.NotImplemented("operation entries.ListEntries has not yet been implemented")
		}),

		LinksListLinksHandler: links.ListLinksHandlerFunc(func(params links.ListLinksParams) middleware.Responder {
			_ = params

			return middleware.NotImplemented("operation links.ListLinks has not yet been implemented")
		}),

		EntriesUpdateEntryHandler: entries.UpdateEntryHandlerFunc(func(params entries.UpdateEntryParams) middleware.Responder {
			_ = params

			return middleware.NotImplemented("operation entries.UpdateEntry has not yet been implemented")
		}),

		LinksUpdateLinkHandler: links.UpdateLinkHandlerFunc(func(params links.UpdateLinkParams) middleware.Responder {
			_ = params

			return middleware.NotImplemented("operation links.UpdateLink has not yet been implemented")
		}),
	}
}

/*IsproAppAPI Mindmap application with entries and links */
type IsproAppAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	customConsumers map[string]runtime.Consumer
	customProducers map[string]runtime.Producer
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler
	useSwaggerUI    bool

	// BasicAuthenticator generates a runtime.Authenticator from the supplied basic auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BasicAuthenticator func(security.UserPassAuthentication) runtime.Authenticator

	// APIKeyAuthenticator generates a runtime.Authenticator from the supplied token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	APIKeyAuthenticator func(string, string, security.TokenAuthentication) runtime.Authenticator

	// BearerAuthenticator generates a runtime.Authenticator from the supplied bearer token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BearerAuthenticator func(string, security.ScopedTokenAuthentication) runtime.Authenticator

	// JSONConsumer registers a consumer for the following mime types:
	//   - application/json
	JSONConsumer runtime.Consumer

	// JSONProducer registers a producer for the following mime types:
	//   - application/json
	JSONProducer runtime.Producer

	// EntriesCreateEntryHandler sets the operation handler for the create entry operation
	EntriesCreateEntryHandler entries.CreateEntryHandler
	// LinksCreateLinkHandler sets the operation handler for the create link operation
	LinksCreateLinkHandler links.CreateLinkHandler
	// EntriesDeleteEntryHandler sets the operation handler for the delete entry operation
	EntriesDeleteEntryHandler entries.DeleteEntryHandler
	// LinksDeleteLinkHandler sets the operation handler for the delete link operation
	LinksDeleteLinkHandler links.DeleteLinkHandler
	// EntriesGetEntryHandler sets the operation handler for the get entry operation
	EntriesGetEntryHandler entries.GetEntryHandler
	// LinksGetLinkHandler sets the operation handler for the get link operation
	LinksGetLinkHandler links.GetLinkHandler
	// EntriesListEntriesHandler sets the operation handler for the list entries operation
	EntriesListEntriesHandler entries.ListEntriesHandler
	// LinksListLinksHandler sets the operation handler for the list links operation
	LinksListLinksHandler links.ListLinksHandler
	// EntriesUpdateEntryHandler sets the operation handler for the update entry operation
	EntriesUpdateEntryHandler entries.UpdateEntryHandler
	// LinksUpdateLinkHandler sets the operation handler for the update link operation
	LinksUpdateLinkHandler links.UpdateLinkHandler

	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// PreServerShutdown is called before the HTTP(S) server is shutdown
	// This allows for custom functions to get executed before the HTTP(S) server stops accepting traffic
	PreServerShutdown func()

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...any)
}

// UseRedoc for documentation at /docs
func (o *IsproAppAPI) UseRedoc() {
	o.useSwaggerUI = false
}

// UseSwaggerUI for documentation at /docs
func (o *IsproAppAPI) UseSwaggerUI() {
	o.useSwaggerUI = true
}

// SetDefaultProduces sets the default produces media type
func (o *IsproAppAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *IsproAppAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// SetSpec sets a spec that will be served for the clients.
func (o *IsproAppAPI) SetSpec(spec *loads.Document) {
	o.spec = spec
}

// DefaultProduces returns the default produces media type
func (o *IsproAppAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *IsproAppAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *IsproAppAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *IsproAppAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the IsproAppAPI
func (o *IsproAppAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}

	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.EntriesCreateEntryHandler == nil {
		unregistered = append(unregistered, "entries.CreateEntryHandler")
	}
	if o.LinksCreateLinkHandler == nil {
		unregistered = append(unregistered, "links.CreateLinkHandler")
	}
	if o.EntriesDeleteEntryHandler == nil {
		unregistered = append(unregistered, "entries.DeleteEntryHandler")
	}
	if o.LinksDeleteLinkHandler == nil {
		unregistered = append(unregistered, "links.DeleteLinkHandler")
	}
	if o.EntriesGetEntryHandler == nil {
		unregistered = append(unregistered, "entries.GetEntryHandler")
	}
	if o.LinksGetLinkHandler == nil {
		unregistered = append(unregistered, "links.GetLinkHandler")
	}
	if o.EntriesListEntriesHandler == nil {
		unregistered = append(unregistered, "entries.ListEntriesHandler")
	}
	if o.LinksListLinksHandler == nil {
		unregistered = append(unregistered, "links.ListLinksHandler")
	}
	if o.EntriesUpdateEntryHandler == nil {
		unregistered = append(unregistered, "entries.UpdateEntryHandler")
	}
	if o.LinksUpdateLinkHandler == nil {
		unregistered = append(unregistered, "links.UpdateLinkHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *IsproAppAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *IsproAppAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {
	return nil
}

// Authorizer returns the registered authorizer
func (o *IsproAppAPI) Authorizer() runtime.Authorizer {
	return nil
}

// ConsumersFor gets the consumers for the specified media types.
//
// MIME type parameters are ignored here.
func (o *IsproAppAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {
	result := make(map[string]runtime.Consumer, len(mediaTypes))
	for _, mt := range mediaTypes {
		if mt == "application/json" {
			result["application/json"] = o.JSONConsumer
		}

		if c, ok := o.customConsumers[mt]; ok {
			result[mt] = c
		}
	}

	return result
}

// ProducersFor gets the producers for the specified media types.
//
// MIME type parameters are ignored here.
func (o *IsproAppAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {
	result := make(map[string]runtime.Producer, len(mediaTypes))
	for _, mt := range mediaTypes {
		if mt == "application/json" {
			result["application/json"] = o.JSONProducer
		}

		if p, ok := o.customProducers[mt]; ok {
			result[mt] = p
		}
	}

	return result
}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *IsproAppAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	if path == "/" {
		path = ""
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

// Context returns the middleware context for the ispro app API
func (o *IsproAppAPI) Context() *middleware.Context {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	return o.context
}

func (o *IsproAppAPI) initHandlerCache() {
	o.Context() // don't care about the result, just that the initialization happened
	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/entries"] = entries.NewCreateEntry(o.context, o.EntriesCreateEntryHandler)
	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/links"] = links.NewCreateLink(o.context, o.LinksCreateLinkHandler)
	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/entries/{id}"] = entries.NewDeleteEntry(o.context, o.EntriesDeleteEntryHandler)
	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/links/{id}"] = links.NewDeleteLink(o.context, o.LinksDeleteLinkHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/entries/{id}"] = entries.NewGetEntry(o.context, o.EntriesGetEntryHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/links/{id}"] = links.NewGetLink(o.context, o.LinksGetLinkHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/entries"] = entries.NewListEntries(o.context, o.EntriesListEntriesHandler)
	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/links"] = links.NewListLinks(o.context, o.LinksListLinksHandler)
	if o.handlers["PUT"] == nil {
		o.handlers["PUT"] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/entries/{id}"] = entries.NewUpdateEntry(o.context, o.EntriesUpdateEntryHandler)
	if o.handlers["PUT"] == nil {
		o.handlers["PUT"] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/links/{id}"] = links.NewUpdateLink(o.context, o.LinksUpdateLinkHandler)
}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *IsproAppAPI) Serve(builder middleware.Builder) http.Handler {
	o.Init()

	if o.Middleware != nil {
		return o.Middleware(builder)
	}
	if o.useSwaggerUI {
		return o.context.APIHandlerSwaggerUI(builder)
	}
	return o.context.APIHandler(builder)
}

// Init allows you to just initialize the handler cache, you can then recompose the middleware as you see fit
func (o *IsproAppAPI) Init() {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}
}

// RegisterConsumer allows you to add (or override) a consumer for a media type.
func (o *IsproAppAPI) RegisterConsumer(mediaType string, consumer runtime.Consumer) {
	o.customConsumers[mediaType] = consumer
}

// RegisterProducer allows you to add (or override) a producer for a media type.
func (o *IsproAppAPI) RegisterProducer(mediaType string, producer runtime.Producer) {
	o.customProducers[mediaType] = producer
}

// AddMiddlewareFor adds a http middleware to existing handler
func (o *IsproAppAPI) AddMiddlewareFor(method, path string, builder middleware.Builder) {
	um := strings.ToUpper(method)
	if path == "/" {
		path = ""
	}
	o.Init()
	if h, ok := o.handlers[um][path]; ok {
		o.handlers[um][path] = builder(h)
	}
}
