// Code generated by go-swagger; DO NOT EDIT.

package links

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/mkheyfets/ispro-app/internal/models"
)

// CreateLinkCreatedCode is the HTTP code returned for type CreateLinkCreated
const CreateLinkCreatedCode int = 201

/*
CreateLinkCreated Link created

swagger:response createLinkCreated
*/
type CreateLinkCreated struct {

	/*
	  In: Body
	*/
	Payload *models.Link `json:"body,omitempty"`
}

// NewCreateLinkCreated creates CreateLinkCreated with default headers values
func NewCreateLinkCreated() *CreateLinkCreated {

	return &CreateLinkCreated{}
}

// WithPayload adds the payload to the create link created response
func (o *CreateLinkCreated) WithPayload(payload *models.Link) *CreateLinkCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create link created response
func (o *CreateLinkCreated) SetPayload(payload *models.Link) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateLinkCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
