// Code generated by go-swagger; DO NOT EDIT.

package links

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// CreateLinkHandlerFunc turns a function with the right signature into a create link handler
type CreateLinkHandlerFunc func(CreateLinkParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateLinkHandlerFunc) Handle(params CreateLinkParams) middleware.Responder {
	return fn(params)
}

// CreateLinkHandler interface for that can handle valid create link params
type CreateLinkHandler interface {
	Handle(CreateLinkParams) middleware.Responder
}

// NewCreateLink creates a new http.Handler for the create link operation
func NewCreateLink(ctx *middleware.Context, handler CreateLinkHandler) *CreateLink {
	return &CreateLink{Context: ctx, Handler: handler}
}

/*
	CreateLink swagger:route POST /links links createLink

Create a new link
*/
type CreateLink struct {
	Context *middleware.Context
	Handler CreateLinkHandler
}

func (o *CreateLink) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewCreateLinkParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
