// Code generated by go-swagger; DO NOT EDIT.

package links

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteLinkNoContentCode is the HTTP code returned for type DeleteLinkNoContent
const DeleteLinkNoContentCode int = 204

/*
DeleteLinkNoContent Link deleted

swagger:response deleteLinkNoContent
*/
type DeleteLinkNoContent struct {
}

// NewDeleteLinkNoContent creates DeleteLinkNoContent with default headers values
func NewDeleteLinkNoContent() *DeleteLinkNoContent {

	return &DeleteLinkNoContent{}
}

// WriteResponse to the client
func (o *DeleteLinkNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) // Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// DeleteLinkNotFoundCode is the HTTP code returned for type DeleteLinkNotFound
const DeleteLinkNotFoundCode int = 404

/*
DeleteLinkNotFound Link not found

swagger:response deleteLinkNotFound
*/
type DeleteLinkNotFound struct {
}

// NewDeleteLinkNotFound creates DeleteLinkNotFound with default headers values
func NewDeleteLinkNotFound() *DeleteLinkNotFound {

	return &DeleteLinkNotFound{}
}

// WriteResponse to the client
func (o *DeleteLinkNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) // Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
