// Code generated by go-swagger; DO NOT EDIT.

package links

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteLinkHandlerFunc turns a function with the right signature into a delete link handler
type DeleteLinkHandlerFunc func(DeleteLinkParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteLinkHandlerFunc) Handle(params DeleteLinkParams) middleware.Responder {
	return fn(params)
}

// DeleteLinkHandler interface for that can handle valid delete link params
type DeleteLinkHandler interface {
	Handle(DeleteLinkParams) middleware.Responder
}

// NewDeleteLink creates a new http.Handler for the delete link operation
func NewDeleteLink(ctx *middleware.Context, handler DeleteLinkHandler) *DeleteLink {
	return &DeleteLink{Context: ctx, Handler: handler}
}

/*
	DeleteLink swagger:route DELETE /links/{id} links deleteLink

Delete link
*/
type DeleteLink struct {
	Context *middleware.Context
	Handler DeleteLinkHandler
}

func (o *DeleteLink) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteLinkParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
