// Code generated by go-swagger; DO NOT EDIT.

package links

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/mkheyfets/ispro-app/internal/models"
)

// GetLinkOKCode is the HTTP code returned for type GetLinkOK
const GetLinkOKCode int = 200

/*
GetLinkOK Link found

swagger:response getLinkOK
*/
type GetLinkOK struct {

	/*
	  In: Body
	*/
	Payload *models.Link `json:"body,omitempty"`
}

// NewGetLinkOK creates GetLinkOK with default headers values
func NewGetLinkOK() *GetLinkOK {

	return &GetLinkOK{}
}

// WithPayload adds the payload to the get link o k response
func (o *GetLinkOK) WithPayload(payload *models.Link) *GetLinkOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get link o k response
func (o *GetLinkOK) SetPayload(payload *models.Link) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetLinkOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetLinkNotFoundCode is the HTTP code returned for type GetLinkNotFound
const GetLinkNotFoundCode int = 404

/*
GetLinkNotFound Link not found

swagger:response getLinkNotFound
*/
type GetLinkNotFound struct {
}

// NewGetLinkNotFound creates GetLinkNotFound with default headers values
func NewGetLinkNotFound() *GetLinkNotFound {

	return &GetLinkNotFound{}
}

// WriteResponse to the client
func (o *GetLinkNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) // Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
