// Code generated by go-swagger; DO NOT EDIT.

package links

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ListLinksHandlerFunc turns a function with the right signature into a list links handler
type ListLinksHandlerFunc func(ListLinksParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ListLinksHandlerFunc) Handle(params ListLinksParams) middleware.Responder {
	return fn(params)
}

// ListLinksHandler interface for that can handle valid list links params
type ListLinksHandler interface {
	Handle(ListLinksParams) middleware.Responder
}

// NewListLinks creates a new http.Handler for the list links operation
func NewListLinks(ctx *middleware.Context, handler ListLinksHandler) *ListLinks {
	return &ListLinks{Context: ctx, Handler: handler}
}

/*
	ListLinks swagger:route GET /links links listLinks

List all links
*/
type ListLinks struct {
	Context *middleware.Context
	Handler ListLinksHandler
}

func (o *ListLinks) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewListLinksParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
