// Code generated by go-swagger; DO NOT EDIT.

package links

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
)

// NewListLinksParams creates a new ListLinksParams object
//
// There are no default values defined in the spec.
func NewListLinksParams() ListLinksParams {

	return ListLinksParams{}
}

// ListLinksParams contains all the bound params for the list links operation
// typically these are obtained from a http.Request
//
// swagger:parameters listLinks
type ListLinksParams struct {
	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewListLinksParams() beforehand.
func (o *ListLinksParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
