// Code generated by go-swagger; DO NOT EDIT.

package links

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// UpdateLinkHandlerFunc turns a function with the right signature into a update link handler
type UpdateLinkHandlerFunc func(UpdateLinkParams) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateLinkHandlerFunc) Handle(params UpdateLinkParams) middleware.Responder {
	return fn(params)
}

// UpdateLinkHandler interface for that can handle valid update link params
type UpdateLinkHandler interface {
	Handle(UpdateLinkParams) middleware.Responder
}

// NewUpdateLink creates a new http.Handler for the update link operation
func NewUpdateLink(ctx *middleware.Context, handler UpdateLinkHandler) *UpdateLink {
	return &UpdateLink{Context: ctx, Handler: handler}
}

/*
	UpdateLink swagger:route PUT /links/{id} links updateLink

Update link
*/
type UpdateLink struct {
	Context *middleware.Context
	Handler UpdateLinkHandler
}

func (o *UpdateLink) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewUpdateLinkParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
