// Code generated by go-swagger; DO NOT EDIT.

package links

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/mkheyfets/ispro-app/internal/models"
)

// UpdateLinkOKCode is the HTTP code returned for type UpdateLinkOK
const UpdateLinkOKCode int = 200

/*
UpdateLinkOK Link updated

swagger:response updateLinkOK
*/
type UpdateLinkOK struct {

	/*
	  In: Body
	*/
	Payload *models.Link `json:"body,omitempty"`
}

// NewUpdateLinkOK creates UpdateLinkOK with default headers values
func NewUpdateLinkOK() *UpdateLinkOK {

	return &UpdateLinkOK{}
}

// WithPayload adds the payload to the update link o k response
func (o *UpdateLinkOK) WithPayload(payload *models.Link) *UpdateLinkOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update link o k response
func (o *UpdateLinkOK) SetPayload(payload *models.Link) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateLinkOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdateLinkNotFoundCode is the HTTP code returned for type UpdateLinkNotFound
const UpdateLinkNotFoundCode int = 404

/*
UpdateLinkNotFound Link not found

swagger:response updateLinkNotFound
*/
type UpdateLinkNotFound struct {
}

// NewUpdateLinkNotFound creates UpdateLinkNotFound with default headers values
func NewUpdateLinkNotFound() *UpdateLinkNotFound {

	return &UpdateLinkNotFound{}
}

// WriteResponse to the client
func (o *UpdateLinkNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) // Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
