// Code generated by go-swagger; DO NOT EDIT.

// Package restapi ISPRO Mindmap API
//
//	Mindmap application with entries and links
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /
//	Version: 1.0.0
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
