// Code generated by go-swagger; DO NOT EDIT.

package restapi

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Mindmap application with entries and links",
    "title": "ISPRO Mindmap API",
    "version": "1.0.0"
  },
  "basePath": "/",
  "paths": {
    "/entries": {
      "get": {
        "tags": [
          "entries"
        ],
        "summary": "List all entries",
        "operationId": "listEntries",
        "responses": {
          "200": {
            "description": "List of entries",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Entry"
              }
            }
          }
        }
      },
      "post": {
        "tags": [
          "entries"
        ],
        "summary": "Create a new entry",
        "operationId": "createEntry",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/EntryInput"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Entry created",
            "schema": {
              "$ref": "#/definitions/Entry"
            }
          }
        }
      }
    },
    "/entries/{id}": {
      "get": {
        "tags": [
          "entries"
        ],
        "summary": "Get entry by ID",
        "operationId": "getEntry",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Entry found",
            "schema": {
              "$ref": "#/definitions/Entry"
            }
          },
          "404": {
            "description": "Entry not found"
          }
        }
      },
      "put": {
        "tags": [
          "entries"
        ],
        "summary": "Update entry",
        "operationId": "updateEntry",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/EntryInput"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Entry updated",
            "schema": {
              "$ref": "#/definitions/Entry"
            }
          },
          "404": {
            "description": "Entry not found"
          }
        }
      },
      "delete": {
        "tags": [
          "entries"
        ],
        "summary": "Delete entry",
        "operationId": "deleteEntry",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "204": {
            "description": "Entry deleted"
          },
          "404": {
            "description": "Entry not found"
          }
        }
      }
    },
    "/links": {
      "get": {
        "tags": [
          "links"
        ],
        "summary": "List all links",
        "operationId": "listLinks",
        "responses": {
          "200": {
            "description": "List of links",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Link"
              }
            }
          }
        }
      },
      "post": {
        "tags": [
          "links"
        ],
        "summary": "Create a new link",
        "operationId": "createLink",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/LinkInput"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Link created",
            "schema": {
              "$ref": "#/definitions/Link"
            }
          }
        }
      }
    },
    "/links/{id}": {
      "get": {
        "tags": [
          "links"
        ],
        "summary": "Get link by ID",
        "operationId": "getLink",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Link found",
            "schema": {
              "$ref": "#/definitions/Link"
            }
          },
          "404": {
            "description": "Link not found"
          }
        }
      },
      "put": {
        "tags": [
          "links"
        ],
        "summary": "Update link",
        "operationId": "updateLink",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/LinkInput"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Link updated",
            "schema": {
              "$ref": "#/definitions/Link"
            }
          },
          "404": {
            "description": "Link not found"
          }
        }
      },
      "delete": {
        "tags": [
          "links"
        ],
        "summary": "Delete link",
        "operationId": "deleteLink",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "204": {
            "description": "Link deleted"
          },
          "404": {
            "description": "Link not found"
          }
        }
      }
    }
  },
  "definitions": {
    "Entry": {
      "type": "object",
      "properties": {
        "content": {
          "type": "string"
        },
        "created_at": {
          "type": "string",
          "format": "date-time"
        },
        "id": {
          "type": "integer",
          "format": "int64"
        },
        "title": {
          "type": "string"
        },
        "updated_at": {
          "type": "string",
          "format": "date-time"
        }
      }
    },
    "EntryInput": {
      "type": "object",
      "required": [
        "title"
      ],
      "properties": {
        "content": {
          "type": "string"
        },
        "title": {
          "type": "string"
        }
      }
    },
    "Link": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer",
          "format": "int64"
        },
        "source_id": {
          "type": "integer",
          "format": "int64"
        },
        "target_id": {
          "type": "integer",
          "format": "int64"
        }
      }
    },
    "LinkInput": {
      "type": "object",
      "required": [
        "source_id",
        "target_id"
      ],
      "properties": {
        "source_id": {
          "type": "integer",
          "format": "int64"
        },
        "target_id": {
          "type": "integer",
          "format": "int64"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Mindmap application with entries and links",
    "title": "ISPRO Mindmap API",
    "version": "1.0.0"
  },
  "basePath": "/",
  "paths": {
    "/entries": {
      "get": {
        "tags": [
          "entries"
        ],
        "summary": "List all entries",
        "operationId": "listEntries",
        "responses": {
          "200": {
            "description": "List of entries",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Entry"
              }
            }
          }
        }
      },
      "post": {
        "tags": [
          "entries"
        ],
        "summary": "Create a new entry",
        "operationId": "createEntry",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/EntryInput"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Entry created",
            "schema": {
              "$ref": "#/definitions/Entry"
            }
          }
        }
      }
    },
    "/entries/{id}": {
      "get": {
        "tags": [
          "entries"
        ],
        "summary": "Get entry by ID",
        "operationId": "getEntry",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Entry found",
            "schema": {
              "$ref": "#/definitions/Entry"
            }
          },
          "404": {
            "description": "Entry not found"
          }
        }
      },
      "put": {
        "tags": [
          "entries"
        ],
        "summary": "Update entry",
        "operationId": "updateEntry",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/EntryInput"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Entry updated",
            "schema": {
              "$ref": "#/definitions/Entry"
            }
          },
          "404": {
            "description": "Entry not found"
          }
        }
      },
      "delete": {
        "tags": [
          "entries"
        ],
        "summary": "Delete entry",
        "operationId": "deleteEntry",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "204": {
            "description": "Entry deleted"
          },
          "404": {
            "description": "Entry not found"
          }
        }
      }
    },
    "/links": {
      "get": {
        "tags": [
          "links"
        ],
        "summary": "List all links",
        "operationId": "listLinks",
        "responses": {
          "200": {
            "description": "List of links",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/Link"
              }
            }
          }
        }
      },
      "post": {
        "tags": [
          "links"
        ],
        "summary": "Create a new link",
        "operationId": "createLink",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/LinkInput"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Link created",
            "schema": {
              "$ref": "#/definitions/Link"
            }
          }
        }
      }
    },
    "/links/{id}": {
      "get": {
        "tags": [
          "links"
        ],
        "summary": "Get link by ID",
        "operationId": "getLink",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Link found",
            "schema": {
              "$ref": "#/definitions/Link"
            }
          },
          "404": {
            "description": "Link not found"
          }
        }
      },
      "put": {
        "tags": [
          "links"
        ],
        "summary": "Update link",
        "operationId": "updateLink",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "name": "id",
            "in": "path",
            "required": true
          },
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/LinkInput"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Link updated",
            "schema": {
              "$ref": "#/definitions/Link"
            }
          },
          "404": {
            "description": "Link not found"
          }
        }
      },
      "delete": {
        "tags": [
          "links"
        ],
        "summary": "Delete link",
        "operationId": "deleteLink",
        "parameters": [
          {
            "type": "integer",
            "format": "int64",
            "name": "id",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "204": {
            "description": "Link deleted"
          },
          "404": {
            "description": "Link not found"
          }
        }
      }
    }
  },
  "definitions": {
    "Entry": {
      "type": "object",
      "properties": {
        "content": {
          "type": "string"
        },
        "created_at": {
          "type": "string",
          "format": "date-time"
        },
        "id": {
          "type": "integer",
          "format": "int64"
        },
        "title": {
          "type": "string"
        },
        "updated_at": {
          "type": "string",
          "format": "date-time"
        }
      }
    },
    "EntryInput": {
      "type": "object",
      "required": [
        "title"
      ],
      "properties": {
        "content": {
          "type": "string"
        },
        "title": {
          "type": "string"
        }
      }
    },
    "Link": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer",
          "format": "int64"
        },
        "source_id": {
          "type": "integer",
          "format": "int64"
        },
        "target_id": {
          "type": "integer",
          "format": "int64"
        }
      }
    },
    "LinkInput": {
      "type": "object",
      "required": [
        "source_id",
        "target_id"
      ],
      "properties": {
        "source_id": {
          "type": "integer",
          "format": "int64"
        },
        "target_id": {
          "type": "integer",
          "format": "int64"
        }
      }
    }
  }
}`))
}
