// Code generated by DIGEN; DO NOT EDIT.
// This file was generated by Dependency Injection Container Generator 0.4.0.
// See docs at https://github.com/strider2038/digen
package di

import (
	"context"
	"errors"
	"fmt"
	pgxpool "github.com/jackc/pgx/v5/pgxpool"
	internal "github.com/mkheyfets/ispro-app/internal/di/internal"
	entryHandler "github.com/mkheyfets/ispro-app/internal/entities/entry"
	entryRepo "github.com/mkheyfets/ispro-app/internal/entities/entry/repository"
	linkHandler "github.com/mkheyfets/ispro-app/internal/entities/link"
	linkRepo "github.com/mkheyfets/ispro-app/internal/entities/link/repository"
	restapi "github.com/mkheyfets/ispro-app/internal/restapi"
	operations "github.com/mkheyfets/ispro-app/internal/restapi/operations"
	validation "github.com/muonsoft/validation"
	"sync"
)

type Container struct {
	mu *sync.Mutex
	c  *internal.Container
}

type Injector func(c *Container) error

func NewContainer(injectors ...Injector) (*Container, error) {
	c := &Container{
		c:  internal.NewContainer(),
		mu: &sync.Mutex{},
	}

	for _, inject := range injectors {
		err := inject(c)
		if err != nil {
			return nil, err
		}
	}

	return c, nil
}

func SetDSN(s string) Injector {
	return func(c *Container) error {
		c.c.SetDSN(s)

		return nil
	}
}

func (c *Container) Pool(ctx context.Context) (s *pgxpool.Pool, err error) {
	c.mu.Lock()
	defer c.mu.Unlock()

	defer func() {
		if recovered := recover(); recovered != nil {
			err = newRecoveredError(recovered, c.c.Error())
		}
	}()

	s = c.c.Pool(ctx)
	err = c.c.Error()

	return s, err
}

func (c *Container) Validator(ctx context.Context) (s *validation.Validator, err error) {
	c.mu.Lock()
	defer c.mu.Unlock()

	defer func() {
		if recovered := recover(); recovered != nil {
			err = newRecoveredError(recovered, c.c.Error())
		}
	}()

	s = c.c.Validator(ctx)
	err = c.c.Error()

	return s, err
}

func (c *Container) EntryRepository(ctx context.Context) (s *entryRepo.PostgresRepository, err error) {
	c.mu.Lock()
	defer c.mu.Unlock()

	defer func() {
		if recovered := recover(); recovered != nil {
			err = newRecoveredError(recovered, c.c.Error())
		}
	}()

	s = c.c.EntryRepository(ctx)
	err = c.c.Error()

	return s, err
}

func (c *Container) LinkRepository(ctx context.Context) (s *linkRepo.PostgresLinkRepository, err error) {
	c.mu.Lock()
	defer c.mu.Unlock()

	defer func() {
		if recovered := recover(); recovered != nil {
			err = newRecoveredError(recovered, c.c.Error())
		}
	}()

	s = c.c.LinkRepository(ctx)
	err = c.c.Error()

	return s, err
}

func (c *Container) EntryHandler(ctx context.Context) (s *entryHandler.Handler, err error) {
	c.mu.Lock()
	defer c.mu.Unlock()

	defer func() {
		if recovered := recover(); recovered != nil {
			err = newRecoveredError(recovered, c.c.Error())
		}
	}()

	s = c.c.EntryHandler(ctx)
	err = c.c.Error()

	return s, err
}

func (c *Container) LinkHandler(ctx context.Context) (s *linkHandler.Handler, err error) {
	c.mu.Lock()
	defer c.mu.Unlock()

	defer func() {
		if recovered := recover(); recovered != nil {
			err = newRecoveredError(recovered, c.c.Error())
		}
	}()

	s = c.c.LinkHandler(ctx)
	err = c.c.Error()

	return s, err
}

func (c *Container) API(ctx context.Context) (s *operations.IsproAppAPI, err error) {
	c.mu.Lock()
	defer c.mu.Unlock()

	defer func() {
		if recovered := recover(); recovered != nil {
			err = newRecoveredError(recovered, c.c.Error())
		}
	}()

	s = c.c.API(ctx)
	err = c.c.Error()

	return s, err
}

func (c *Container) Server(ctx context.Context) (s *restapi.Server, err error) {
	c.mu.Lock()
	defer c.mu.Unlock()

	defer func() {
		if recovered := recover(); recovered != nil {
			err = newRecoveredError(recovered, c.c.Error())
		}
	}()

	s = c.c.Server(ctx)
	err = c.c.Error()

	return s, err
}

func (c *Container) Close() {
	c.mu.Lock()
	defer c.mu.Unlock()

	c.c.Close()
}

func newRecoveredError(recovered any, err error) error {
	r := fmt.Errorf("panic: %v", recovered)
	if err != nil {
		return errors.Join(r, fmt.Errorf("previous error: %w", err))
	}
	return r
}
