// Code generated by go-swagger; DO NOT EDIT.

package links

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/mkheyfets/ispro-app/models"
)

// ListLinksOKCode is the HTTP code returned for type ListLinksOK
const ListLinksOKCode int = 200

/*
ListLinksOK List of links

swagger:response listLinksOK
*/
type ListLinksOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Link `json:"body,omitempty"`
}

// NewListLinksOK creates ListLinksOK with default headers values
func NewListLinksOK() *ListLinksOK {

	return &ListLinksOK{}
}

// WithPayload adds the payload to the list links o k response
func (o *ListLinksOK) WithPayload(payload []*models.Link) *ListLinksOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list links o k response
func (o *ListLinksOK) SetPayload(payload []*models.Link) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListLinksOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Link, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
