// Code generated by go-swagger; DO NOT EDIT.

package entries

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/mkheyfets/ispro-app/internal/models"
)

// CreateEntryCreatedCode is the HTTP code returned for type CreateEntryCreated
const CreateEntryCreatedCode int = 201

/*
CreateEntryCreated Entry created

swagger:response createEntryCreated
*/
type CreateEntryCreated struct {

	/*
	  In: Body
	*/
	Payload *models.Entry `json:"body,omitempty"`
}

// NewCreateEntryCreated creates CreateEntryCreated with default headers values
func NewCreateEntryCreated() *CreateEntryCreated {

	return &CreateEntryCreated{}
}

// WithPayload adds the payload to the create entry created response
func (o *CreateEntryCreated) WithPayload(payload *models.Entry) *CreateEntryCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create entry created response
func (o *CreateEntryCreated) SetPayload(payload *models.Entry) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreateEntryCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
