// Code generated by go-swagger; DO NOT EDIT.

package entries

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// CreateEntryHandlerFunc turns a function with the right signature into a create entry handler
type CreateEntryHandlerFunc func(CreateEntryParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateEntryHandlerFunc) Handle(params CreateEntryParams) middleware.Responder {
	return fn(params)
}

// CreateEntryHandler interface for that can handle valid create entry params
type CreateEntryHandler interface {
	Handle(CreateEntryParams) middleware.Responder
}

// NewCreateEntry creates a new http.Handler for the create entry operation
func NewCreateEntry(ctx *middleware.Context, handler CreateEntryHandler) *CreateEntry {
	return &CreateEntry{Context: ctx, Handler: handler}
}

/*
	CreateEntry swagger:route POST /entries entries createEntry

Create a new entry
*/
type CreateEntry struct {
	Context *middleware.Context
	Handler CreateEntryHandler
}

func (o *CreateEntry) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewCreateEntryParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
