// Code generated by go-swagger; DO NOT EDIT.

package entries

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeleteEntryNoContentCode is the HTTP code returned for type DeleteEntryNoContent
const DeleteEntryNoContentCode int = 204

/*
DeleteEntryNoContent Entry deleted

swagger:response deleteEntryNoContent
*/
type DeleteEntryNoContent struct {
}

// NewDeleteEntryNoContent creates DeleteEntryNoContent with default headers values
func NewDeleteEntryNoContent() *DeleteEntryNoContent {

	return &DeleteEntryNoContent{}
}

// WriteResponse to the client
func (o *DeleteEntryNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) // Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// DeleteEntryNotFoundCode is the HTTP code returned for type DeleteEntryNotFound
const DeleteEntryNotFoundCode int = 404

/*
DeleteEntryNotFound Entry not found

swagger:response deleteEntryNotFound
*/
type DeleteEntryNotFound struct {
}

// NewDeleteEntryNotFound creates DeleteEntryNotFound with default headers values
func NewDeleteEntryNotFound() *DeleteEntryNotFound {

	return &DeleteEntryNotFound{}
}

// WriteResponse to the client
func (o *DeleteEntryNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) // Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
