// Code generated by go-swagger; DO NOT EDIT.

package entries

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/mkheyfets/ispro-app/internal/models"
)

// GetEntryOKCode is the HTTP code returned for type GetEntryOK
const GetEntryOKCode int = 200

/*
GetEntryOK Entry found

swagger:response getEntryOK
*/
type GetEntryOK struct {

	/*
	  In: Body
	*/
	Payload *models.Entry `json:"body,omitempty"`
}

// NewGetEntryOK creates GetEntryOK with default headers values
func NewGetEntryOK() *GetEntryOK {

	return &GetEntryOK{}
}

// WithPayload adds the payload to the get entry o k response
func (o *GetEntryOK) WithPayload(payload *models.Entry) *GetEntryOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get entry o k response
func (o *GetEntryOK) SetPayload(payload *models.Entry) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetEntryOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetEntryNotFoundCode is the HTTP code returned for type GetEntryNotFound
const GetEntryNotFoundCode int = 404

/*
GetEntryNotFound Entry not found

swagger:response getEntryNotFound
*/
type GetEntryNotFound struct {
}

// NewGetEntryNotFound creates GetEntryNotFound with default headers values
func NewGetEntryNotFound() *GetEntryNotFound {

	return &GetEntryNotFound{}
}

// WriteResponse to the client
func (o *GetEntryNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) // Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
