// Code generated by go-swagger; DO NOT EDIT.

package entries

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// ListEntriesHandlerFunc turns a function with the right signature into a list entries handler
type ListEntriesHandlerFunc func(ListEntriesParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ListEntriesHandlerFunc) Handle(params ListEntriesParams) middleware.Responder {
	return fn(params)
}

// ListEntriesHandler interface for that can handle valid list entries params
type ListEntriesHandler interface {
	Handle(ListEntriesParams) middleware.Responder
}

// NewListEntries creates a new http.Handler for the list entries operation
func NewListEntries(ctx *middleware.Context, handler ListEntriesHandler) *ListEntries {
	return &ListEntries{Context: ctx, Handler: handler}
}

/*
	ListEntries swagger:route GET /entries entries listEntries

List all entries
*/
type ListEntries struct {
	Context *middleware.Context
	Handler ListEntriesHandler
}

func (o *ListEntries) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewListEntriesParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
