// Code generated by go-swagger; DO NOT EDIT.

package entries

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/mkheyfets/ispro-app/internal/models"
)

// ListEntriesOKCode is the HTTP code returned for type ListEntriesOK
const ListEntriesOKCode int = 200

/*
ListEntriesOK List of entries

swagger:response listEntriesOK
*/
type ListEntriesOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Entry `json:"body,omitempty"`
}

// NewListEntriesOK creates ListEntriesOK with default headers values
func NewListEntriesOK() *ListEntriesOK {

	return &ListEntriesOK{}
}

// WithPayload adds the payload to the list entries o k response
func (o *ListEntriesOK) WithPayload(payload []*models.Entry) *ListEntriesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the list entries o k response
func (o *ListEntriesOK) SetPayload(payload []*models.Entry) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *ListEntriesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Entry, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
