// Code generated by go-swagger; DO NOT EDIT.

package entries

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// UpdateEntryHandlerFunc turns a function with the right signature into a update entry handler
type UpdateEntryHandlerFunc func(UpdateEntryParams) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateEntryHandlerFunc) Handle(params UpdateEntryParams) middleware.Responder {
	return fn(params)
}

// UpdateEntryHandler interface for that can handle valid update entry params
type UpdateEntryHandler interface {
	Handle(UpdateEntryParams) middleware.Responder
}

// NewUpdateEntry creates a new http.Handler for the update entry operation
func NewUpdateEntry(ctx *middleware.Context, handler UpdateEntryHandler) *UpdateEntry {
	return &UpdateEntry{Context: ctx, Handler: handler}
}

/*
	UpdateEntry swagger:route PUT /entries/{id} entries updateEntry

Update entry
*/
type UpdateEntry struct {
	Context *middleware.Context
	Handler UpdateEntryHandler
}

func (o *UpdateEntry) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewUpdateEntryParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
