// Code generated by DIGEN; DO NOT EDIT.
// This file was generated by Dependency Injection Container Generator 0.4.0.
// See docs at https://github.com/strider2038/digen
package internal

import (
	"context"
	"errors"
	"fmt"
	pgxpool "github.com/jackc/pgx/v5/pgxpool"
	factories "github.com/mkheyfets/ispro-app/internal/di/internal/factories"
	entryHandler "github.com/mkheyfets/ispro-app/internal/entities/entry"
	entryRepo "github.com/mkheyfets/ispro-app/internal/entities/entry/repository"
	linkHandler "github.com/mkheyfets/ispro-app/internal/entities/link"
	linkRepo "github.com/mkheyfets/ispro-app/internal/entities/link/repository"
	restapi "github.com/mkheyfets/ispro-app/internal/restapi"
	operations "github.com/mkheyfets/ispro-app/internal/restapi/operations"
	validation "github.com/muonsoft/validation"
)

const (
	id_DSN = iota
	id_Pool
	id_Validator
	id_EntryRepository
	id_LinkRepository
	id_EntryHandler
	id_LinkHandler
	id_API
	id_Server
)

type Container struct {
	errs []error
	init bitset

	dsn             string
	pool            *pgxpool.Pool
	validator       *validation.Validator
	entryRepository *entryRepo.PostgresRepository
	linkRepository  *linkRepo.PostgresLinkRepository
	entryHandler    *entryHandler.Handler
	linkHandler     *linkHandler.Handler
	api             *operations.IsproAppAPI
	server          *restapi.Server
}

func NewContainer() *Container {
	c := &Container{}
	c.init = make(bitset, 1)

	return c
}

// Error returns the first initialization error, which can be set via SetError in a service definition.
func (c *Container) Error() error {
	return errors.Join(c.errs...)
}

// SetError sets the first error into container. The error is used in the public container to return an initialization error.
// Deprecated. Return error in factory instead.
func (c *Container) SetError(err error) {
	c.addError(err)
}

func (c *Container) addError(err error) {
	if err != nil {
		c.errs = append(c.errs, err)
	}
}

func (c *Container) DSN(ctx context.Context) string {
	if !c.init.IsSet(id_DSN) && c.errs == nil {
		var err error
		c.dsn, err = factories.CreateDSN(ctx, c)
		if err != nil {
			c.addError(fmt.Errorf("create DSN: %w", err))
		} else {
			c.init.Set(id_DSN)
		}
	}
	return c.dsn
}

func (c *Container) Pool(ctx context.Context) *pgxpool.Pool {
	if !c.init.IsSet(id_Pool) && c.errs == nil {
		var err error
		c.pool, err = factories.CreatePool(ctx, c)
		if err != nil {
			c.addError(fmt.Errorf("create Pool: %w", err))
		} else {
			c.init.Set(id_Pool)
		}
	}
	return c.pool
}

func (c *Container) Validator(ctx context.Context) *validation.Validator {
	if !c.init.IsSet(id_Validator) && c.errs == nil {
		var err error
		c.validator, err = factories.CreateValidator(ctx, c)
		if err != nil {
			c.addError(fmt.Errorf("create Validator: %w", err))
		} else {
			c.init.Set(id_Validator)
		}
	}
	return c.validator
}

func (c *Container) EntryRepository(ctx context.Context) *entryRepo.PostgresRepository {
	if !c.init.IsSet(id_EntryRepository) && c.errs == nil {
		var err error
		c.entryRepository, err = factories.CreateEntryRepository(ctx, c)
		if err != nil {
			c.addError(fmt.Errorf("create EntryRepository: %w", err))
		} else {
			c.init.Set(id_EntryRepository)
		}
	}
	return c.entryRepository
}

func (c *Container) LinkRepository(ctx context.Context) *linkRepo.PostgresLinkRepository {
	if !c.init.IsSet(id_LinkRepository) && c.errs == nil {
		var err error
		c.linkRepository, err = factories.CreateLinkRepository(ctx, c)
		if err != nil {
			c.addError(fmt.Errorf("create LinkRepository: %w", err))
		} else {
			c.init.Set(id_LinkRepository)
		}
	}
	return c.linkRepository
}

func (c *Container) EntryHandler(ctx context.Context) *entryHandler.Handler {
	if !c.init.IsSet(id_EntryHandler) && c.errs == nil {
		var err error
		c.entryHandler, err = factories.CreateEntryHandler(ctx, c)
		if err != nil {
			c.addError(fmt.Errorf("create EntryHandler: %w", err))
		} else {
			c.init.Set(id_EntryHandler)
		}
	}
	return c.entryHandler
}

func (c *Container) LinkHandler(ctx context.Context) *linkHandler.Handler {
	if !c.init.IsSet(id_LinkHandler) && c.errs == nil {
		var err error
		c.linkHandler, err = factories.CreateLinkHandler(ctx, c)
		if err != nil {
			c.addError(fmt.Errorf("create LinkHandler: %w", err))
		} else {
			c.init.Set(id_LinkHandler)
		}
	}
	return c.linkHandler
}

func (c *Container) API(ctx context.Context) *operations.IsproAppAPI {
	if !c.init.IsSet(id_API) && c.errs == nil {
		var err error
		c.api, err = factories.CreateAPI(ctx, c)
		if err != nil {
			c.addError(fmt.Errorf("create API: %w", err))
		} else {
			c.init.Set(id_API)
		}
	}
	return c.api
}

func (c *Container) Server(ctx context.Context) *restapi.Server {
	if !c.init.IsSet(id_Server) && c.errs == nil {
		var err error
		c.server, err = factories.CreateServer(ctx, c)
		if err != nil {
			c.addError(fmt.Errorf("create Server: %w", err))
		} else {
			c.init.Set(id_Server)
		}
	}
	return c.server
}

func (c *Container) SetDSN(s string) {
	c.dsn = s
	c.init.Set(id_DSN)
}

func (c *Container) Close() {}
